# Generated by Django 4.2.7 on 2025-10-03 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_category_game_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('token_hash', models.CharField(editable=False, max_length=64, verbose_name='Hash do Token')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Contador de Uso')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.entitlement', verbose_name='Direito de Acesso')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Jogo',
                'verbose_name_plural': 'Tokens de Jogos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
