# Generated by Django 4.2.7 on 2025-11-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_update_game_model_for_tde'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gametoken',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gametoken',
            name='entitlement',
        ),
        migrations.RemoveField(
            model_name='gametoken',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gametoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='game',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='games',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='game',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(max_length=50, verbose_name='Console/Plataforma'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL da imagem de capa do jogo', null=True, verbose_name='URL da Capa'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, help_text='Será gerado automaticamente a partir do título se não fornecido', max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='Entitlement',
        ),
        migrations.DeleteModel(
            name='GameToken',
        ),
        migrations.DeleteModel(
            name='PaymentSession',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
