# Generated by Django 4.2.7 on 2025-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_simplify_game_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o jogo não aparecerá no catálogo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rom_url',
            field=models.URLField(blank=True, help_text='URL completa do jogo no retrogames.cc ou serviço similar. Ex: https://www.retrogames.cc/embed/[ID]. Esta URL será usada diretamente no iframe do emulador.', null=True, verbose_name='URL da ROM/Jogo'),
        ),
    ]
