# Generated by Django 4.2.7 on 2025-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_game_cover_image_alter_game_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL da imagem de capa do jogo (screenshot ou capa). Será exibida nos cards de jogos.', null=True, verbose_name='URL da Imagem de Capa'),
        ),
    ]
