# Generated by Django 4.2.7 on 2025-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_create_gamerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamerequest',
            new_name='games_gamer_status_c8a755_idx',
            old_name='games_gamer_status_5f8a7b_idx',
        ),
        migrations.RenameIndex(
            model_name='gamerequest',
            new_name='games_gamer_user_id_e35b38_idx',
            old_name='games_gamer_user_id_8f2b3c_idx',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='ai_query',
            field=models.CharField(blank=True, help_text='Consulta/nome que será enviado para a IA para obter os dados completos do jogo. Será preenchido automaticamente com uma sugestão baseada no título e console, mas pode ser editado pelo administrador.', max_length=500, verbose_name='Consulta para IA'),
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='ready_for_ai',
            field=models.BooleanField(default=False, help_text='Indica se esta requisição está preparada e pronta para ser enviada à IA para processamento', verbose_name='Pronta para Enviar à IA'),
        ),
    ]
