# Generated by Django 4.2.7 on 2025-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_rename_games_gamer_status_5f8a7b_idx_games_gamer_status_c8a755_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequest',
            name='console',
        ),
        migrations.RemoveField(
            model_name='gamerequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='gamerequest',
            name='rom_url_suggestion',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='details',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre o jogo solicitado', verbose_name='Detalhes do Jogo'),
        ),
    ]
